CREATE DATABASE CHECKPOINT5;
USE CHECKPOINT5
CREATE TABLE PRODUCTS (
		RECORD_ID INT PRIMARY KEY ,
		NAME VARCHAR (50),
		PRICE DECIMAL (10,2),
		)
INSERT INTO PRODUCTS (RECORD_ID, NAME, PRICE)
VALUES (1,'Cookies', 10.00),
		(2, 'Candy', 5.20);
SELECT * FROM PRODUCTS


CREATE TABLE CUSTOMERS (
		RECORD_ID INT PRIMARY KEY,
		NAME VARCHAR (50),
		ADDRESS VARCHAR (100),
		)
INSERT INTO CUSTOMERS(RECORD_ID, NAME, ADDRESS)
VALUES (1, 'Ahmed', 'Tunisia'),
		(2, 'Coulibaly', 'Senegal'),
		(3, 'Hasan', 'Egypt');
SELECT * FROM CUSTOMERS


CREATE TABLE ORDERS (
		ORDER_ID INT PRIMARY KEY,
		customer_id	INT FOREIGN KEY (customer_id) REFERENCES Customers (RECORD_ID),
		product_id INT FOREIGN KEY (product_id) REFERENCES Products (RECORD_ID),
		quantity INT,		
		Order_date DATE DEFAULT GETDATE(),
)
INSERT INTO ORDERS (ORDER_ID, customer_id, product_id, quantity, Order_date)
VALUES (1, 1, 2, 3, '2023-01-22'),
		(2, 2, 1, 10, '2023-04-14');
SELECT * FROM ORDERS

UPDATE ORDERS
SET quantity = 6
WHERE ORDER_ID = 2;
SELECT * FROM ORDERS

DELETE FROM CUSTOMERS
WHERE RECORD_ID = 3;
SELECT * FROM CUSTOMERS;

DELETE ORDERS
WHERE ORDER_ID = 1;
SELECT * FROM ORDERS

DROP TABLE ORDERS;